//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualGGPK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualGGPK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        public static string DatViewer_Button_ExportCSV {
            get {
                return ResourceManager.GetString("DatViewer_Button_ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DatViewer_Button_Save {
            get {
                return ResourceManager.GetString("DatViewer_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save CSV file: {0}.
        /// </summary>
        public static string DatViewer_ExportCSV_Failed {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved CSV file to {0}.
        /// </summary>
        public static string DatViewer_ExportCSV_Successful {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved CSV.
        /// </summary>
        public static string DatViewer_ExportCSV_Successful_Caption {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read dat: {0}.
        /// </summary>
        public static string DatWrapper_ParseDatFile_Failed {
            get {
                return ResourceManager.GetString("DatWrapper_ParseDatFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No handler for file {0}.
        /// </summary>
        public static string DatWrapper_ParseDatFile_Unsupported_File {
            get {
                return ResourceManager.GetString("DatWrapper_ParseDatFile_Unsupported_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save: {0}.
        /// </summary>
        public static string DatWrapper_Save_Failed {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved &apos;{0}&apos;.
        /// </summary>
        public static string DatWrapper_Save_Successful {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string DatWrapper_Save_Successful_Caption {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Caption {
            get {
                return ResourceManager.GetString("Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read directory tree: {0}.
        /// </summary>
        public static string Error_Read_Directory_Tree {
            get {
                return ResourceManager.GetString("Error_Read_Directory_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectedRecord.Name.
        /// </summary>
        public static string ExportAllItemsInDirectory_Default_FileName {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Default_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export item(s): {0}.
        /// </summary>
        public static string ExportAllItemsInDirectory_Failed {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported {0} files.
        /// </summary>
        public static string ExportAllItemsInDirectory_Successful {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successful.
        /// </summary>
        public static string ExportAllItemsInDirectory_Successful_Caption {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export item: {0}.
        /// </summary>
        public static string ExportSelectedItem_Failed {
            get {
                return ResourceManager.GetString("ExportSelectedItem_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported {0} bytes.
        /// </summary>
        public static string ExportSelectedItem_Successful {
            get {
                return ResourceManager.GetString("ExportSelectedItem_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Offset:.
        /// </summary>
        public static string LabelFileOFfset_Content {
            get {
                return ResourceManager.GetString("LabelFileOFfset_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GGPK Pack File|*.ggpk.
        /// </summary>
        public static string Load_GGPK_Filter {
            get {
                return ResourceManager.GetString("Load_GGPK_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only drop a single file, directory, or zip file.
        /// </summary>
        public static string MainWindow_Drop_Failed {
            get {
                return ResourceManager.GetString("MainWindow_Drop_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying contents of {0}.
        /// </summary>
        public static string MainWindow_HandleDropArchive_Info {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropArchive_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File count = {0}.
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Count {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to replace file {0} -&gt; Missing.
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Failed {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing {0}.
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Replace {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a file to replace in the tree view.
        /// </summary>
        public static string MainWindow_HandleDropFile_Failed {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing {0}{1}.
        /// </summary>
        public static string MainWindow_HandleDropFile_Replace {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropFile_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Offset:.
        /// </summary>
        public static string MainWindow_Label_FileOffset {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MainWindow_Menu_Export {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string MainWindow_Menu_Replace {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MainWindow_Menu_View {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualGGPK (Read-Only).
        /// </summary>
        public static string MainWindow_Title_Readonly {
            get {
                return ResourceManager.GetString("MainWindow_Title_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace files?.
        /// </summary>
        public static string MainWindow_Window_Drop_Confirm {
            get {
                return ResourceManager.GetString("MainWindow_Window_Drop_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm replace.
        /// </summary>
        public static string MainWindow_Window_Drop_Confirm_Caption {
            get {
                return ResourceManager.GetString("MainWindow_Window_Drop_Confirm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read file: {0}.
        /// </summary>
        public static string ReloadGGPK_Failed {
            get {
                return ResourceManager.GetString("ReloadGGPK_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***Opening GGPK in read-only mode ***.
        /// </summary>
        public static string ReloadGGPK_ReadOnly {
            get {
                return ResourceManager.GetString("ReloadGGPK_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done!.
        /// </summary>
        public static string ReloadGGPK_Successful {
            get {
                return ResourceManager.GetString("ReloadGGPK_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traversing tree.....
        /// </summary>
        public static string ReloadGGPK_Traversing_Tree {
            get {
                return ResourceManager.GetString("ReloadGGPK_Traversing_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to replace item: {0}.
        /// </summary>
        public static string ReplaceItem_Failed {
            get {
                return ResourceManager.GetString("ReplaceItem_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GGPK open in read-only mode.
        /// </summary>
        public static string ReplaceItem_Readonly {
            get {
                return ResourceManager.GetString("ReplaceItem_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to GGPK.
        /// </summary>
        public static string ReplaceItem_Readonly_Caption {
            get {
                return ResourceManager.GetString("ReplaceItem_Readonly_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record {0} updated and relocated to offset {1}.
        /// </summary>
        public static string ReplaceItem_Successful {
            get {
                return ResourceManager.GetString("ReplaceItem_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement successful.
        /// </summary>
        public static string ReplaceItem_Successful_Caption {
            get {
                return ResourceManager.GetString("ReplaceItem_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Unable to view item, export it if you want to view it *
        ///
        ///Details: {0}.
        /// </summary>
        public static string UpdateDisplayPanel_Failed {
            get {
                return ResourceManager.GetString("UpdateDisplayPanel_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract file for viewing: {0}.
        /// </summary>
        public static string ViewSelectedItem_Failed {
            get {
                return ResourceManager.GetString("ViewSelectedItem_Failed", resourceCulture);
            }
        }
    }
}
