//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualGGPK.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualGGPK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Export CSV 的當地語系化字串。
        /// </summary>
        public static string DatViewer_Button_ExportCSV {
            get {
                return ResourceManager.GetString("DatViewer_Button_ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reload XML 的當地語系化字串。
        /// </summary>
        public static string DatViewer_Button_Reload_XML {
            get {
                return ResourceManager.GetString("DatViewer_Button_Reload_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        public static string DatViewer_Button_Save {
            get {
                return ResourceManager.GetString("DatViewer_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to save CSV file: {0} 的當地語系化字串。
        /// </summary>
        public static string DatViewer_ExportCSV_Failed {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Saved CSV file to {0} 的當地語系化字串。
        /// </summary>
        public static string DatViewer_ExportCSV_Successful {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully saved CSV 的當地語系化字串。
        /// </summary>
        public static string DatViewer_ExportCSV_Successful_Caption {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show dereferenced value at pointer offset 的當地語系化字串。
        /// </summary>
        public static string DatViewer_ShowPointerDataDesciption {
            get {
                return ResourceManager.GetString("DatViewer_ShowPointerDataDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show pointer prefix 的當地語系化字串。
        /// </summary>
        public static string DatViewer_ShowPointerPrefixDesciption {
            get {
                return ResourceManager.GetString("DatViewer_ShowPointerPrefixDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to read dat: {0} 的當地語系化字串。
        /// </summary>
        public static string DatWrapper_ParseDatFile_Failed {
            get {
                return ResourceManager.GetString("DatWrapper_ParseDatFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No handler for file {0} 的當地語系化字串。
        /// </summary>
        public static string DatWrapper_ParseDatFile_Unsupported_File {
            get {
                return ResourceManager.GetString("DatWrapper_ParseDatFile_Unsupported_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to save: {0} 的當地語系化字串。
        /// </summary>
        public static string DatWrapper_Save_Failed {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Saved &apos;{0}&apos; 的當地語系化字串。
        /// </summary>
        public static string DatWrapper_Save_Successful {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Saved 的當地語系化字串。
        /// </summary>
        public static string DatWrapper_Save_Successful_Caption {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        public static string Error_Caption {
            get {
                return ResourceManager.GetString("Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to read directory tree: {0} 的當地語系化字串。
        /// </summary>
        public static string Error_Read_Directory_Tree {
            get {
                return ResourceManager.GetString("Error_Read_Directory_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 selectedRecord.Name 的當地語系化字串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Default_FileName {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Default_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to export item(s): {0} 的當地語系化字串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Failed {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exported {0} files 的當地語系化字串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Successful {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Export successful 的當地語系化字串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Successful_Caption {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to export item: {0} 的當地語系化字串。
        /// </summary>
        public static string ExportSelectedItem_Failed {
            get {
                return ResourceManager.GetString("ExportSelectedItem_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exported {0} bytes 的當地語系化字串。
        /// </summary>
        public static string ExportSelectedItem_Successful {
            get {
                return ResourceManager.GetString("ExportSelectedItem_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File Offset: 的當地語系化字串。
        /// </summary>
        public static string LabelFileOFfset_Content {
            get {
                return ResourceManager.GetString("LabelFileOFfset_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GGPK Pack File|*.ggpk|Records Bin File|*.bin 的當地語系化字串。
        /// </summary>
        public static string Load_GGPK_Filter {
            get {
                return ResourceManager.GetString("Load_GGPK_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can only drop a single file, directory, or zip file 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Drop_Failed {
            get {
                return ResourceManager.GetString("MainWindow_Drop_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Applying contents of {0} 的當地語系化字串。
        /// </summary>
        public static string MainWindow_HandleDropArchive_Info {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropArchive_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File count = {0} 的當地語系化字串。
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Count {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to replace file {0} -&gt; Missing 的當地語系化字串。
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Failed {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Replacing {0} 的當地語系化字串。
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Replace {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Must select a file to replace in the tree view 的當地語系化字串。
        /// </summary>
        public static string MainWindow_HandleDropFile_Failed {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Replacing {0}{1} 的當地語系化字串。
        /// </summary>
        public static string MainWindow_HandleDropFile_Replace {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropFile_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hash: 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Label_FileHash {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name Hash: 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Label_FileNameHash {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileNameHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File Offset: 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Label_FileOffset {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File Size: 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Label_FileSize {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Menu_Delete {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Export 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Menu_Export {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Replace 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Menu_Replace {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 View 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Menu_View {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VisualGGPK (Read-Only) 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Title_Readonly {
            get {
                return ResourceManager.GetString("MainWindow_Title_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Version check failed. 的當地語系化字串。
        /// </summary>
        public static string MainWindow_VersionCheck_Failed {
            get {
                return ResourceManager.GetString("MainWindow_VersionCheck_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Replace files? 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Window_Drop_Confirm {
            get {
                return ResourceManager.GetString("MainWindow_Window_Drop_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm replace 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Window_Drop_Confirm_Caption {
            get {
                return ResourceManager.GetString("MainWindow_Window_Drop_Confirm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to read file: {0} 的當地語系化字串。
        /// </summary>
        public static string ReloadGGPK_Failed {
            get {
                return ResourceManager.GetString("ReloadGGPK_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ***Opening GGPK in read-only mode *** 的當地語系化字串。
        /// </summary>
        public static string ReloadGGPK_ReadOnly {
            get {
                return ResourceManager.GetString("ReloadGGPK_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All done! 的當地語系化字串。
        /// </summary>
        public static string ReloadGGPK_Successful {
            get {
                return ResourceManager.GetString("ReloadGGPK_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Traversing tree.... 的當地語系化字串。
        /// </summary>
        public static string ReloadGGPK_Traversing_Tree {
            get {
                return ResourceManager.GetString("ReloadGGPK_Traversing_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to replace item: {0} 的當地語系化字串。
        /// </summary>
        public static string ReplaceItem_Failed {
            get {
                return ResourceManager.GetString("ReplaceItem_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GGPK open in read-only mode 的當地語系化字串。
        /// </summary>
        public static string ReplaceItem_Readonly {
            get {
                return ResourceManager.GetString("ReplaceItem_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot write to GGPK 的當地語系化字串。
        /// </summary>
        public static string ReplaceItem_Readonly_Caption {
            get {
                return ResourceManager.GetString("ReplaceItem_Readonly_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Record {0} updated and relocated to offset {1} 的當地語系化字串。
        /// </summary>
        public static string ReplaceItem_Successful {
            get {
                return ResourceManager.GetString("ReplaceItem_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Replacement successful 的當地語系化字串。
        /// </summary>
        public static string ReplaceItem_Successful_Caption {
            get {
                return ResourceManager.GetString("ReplaceItem_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  * Unable to view item, export it if you want to view it *
        ///
        ///Details: {0} 的當地語系化字串。
        /// </summary>
        public static string UpdateDisplayPanel_Failed {
            get {
                return ResourceManager.GetString("UpdateDisplayPanel_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to extract file for viewing: {0} 的當地語系化字串。
        /// </summary>
        public static string ViewSelectedItem_Failed {
            get {
                return ResourceManager.GetString("ViewSelectedItem_Failed", resourceCulture);
            }
        }
    }
}
