//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoeStrings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoeStrings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Replacing &apos;{0}&apos; with &apos;{1}&apos;.
        /// </summary>
        public static string ApplyTranslations_TextReplaced {
            get {
                return ResourceManager.GetString("ApplyTranslations_TextReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read {0}: {1}.
        /// </summary>
        public static string CollectTranslatableStrings_FailedReading {
            get {
                return ResourceManager.GetString("CollectTranslatableStrings_FailedReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Strings: {0}.
        /// </summary>
        public static string GetTranslatableDatStrings_TotalStrings {
            get {
                return ResourceManager.GetString("GetTranslatableDatStrings_TotalStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GGPK Pack File|*.ggpk.
        /// </summary>
        public static string Load_GGPK_Filter {
            get {
                return ResourceManager.GetString("Load_GGPK_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply all.
        /// </summary>
        public static string MainWindow_Button_ApplyAll {
            get {
                return ResourceManager.GetString("MainWindow_Button_ApplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply all to File.
        /// </summary>
        public static string MainWindow_Button_ApplyAllToFile {
            get {
                return ResourceManager.GetString("MainWindow_Button_ApplyAllToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert all.
        /// </summary>
        public static string MainWindow_Button_RevertAll {
            get {
                return ResourceManager.GetString("MainWindow_Button_RevertAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save config.
        /// </summary>
        public static string MainWindow_Button_SaveConfig {
            get {
                return ResourceManager.GetString("MainWindow_Button_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file filter for GGPK files: {0}.
        /// </summary>
        public static string MainWindow_InvalidFileFilter {
            get {
                return ResourceManager.GetString("MainWindow_InvalidFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations read: {0}.
        /// </summary>
        public static string ReadTranslationData_Successful {
            get {
                return ResourceManager.GetString("ReadTranslationData_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load config: {0}.
        /// </summary>
        public static string ReloadAllData_Failed {
            get {
                return ResourceManager.GetString("ReloadAllData_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations read: {0}.
        /// </summary>
        public static string SaveTranslationData_Successful {
            get {
                return ResourceManager.GetString("SaveTranslationData_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &apos;{0}&apos;?.
        /// </summary>
        public static string StringEditor_DeleteTranslation {
            get {
                return ResourceManager.GetString("StringEditor_DeleteTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete translation?.
        /// </summary>
        public static string StringEditor_DeleteTranslation_Caption {
            get {
                return ResourceManager.GetString("StringEditor_DeleteTranslation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original:.
        /// </summary>
        public static string StringEditor_Label_Original {
            get {
                return ResourceManager.GetString("StringEditor_Label_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement:.
        /// </summary>
        public static string StringEditor_Label_Replacement {
            get {
                return ResourceManager.GetString("StringEditor_Label_Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement:.
        /// </summary>
        public static string StringEditor_Label_Translation {
            get {
                return ResourceManager.GetString("StringEditor_Label_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file before continuing?.
        /// </summary>
        public static string WindowClosing_Save {
            get {
                return ResourceManager.GetString("WindowClosing_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string WindowClosing_Save_Title {
            get {
                return ResourceManager.GetString("WindowClosing_Save_Title", resourceCulture);
            }
        }
    }
}
