//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoeStrings.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoeStrings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似   Replacing &apos;{0}&apos; with &apos;{1}&apos; 的當地語系化字串。
        /// </summary>
        public static string ApplyTranslations_TextReplaced {
            get {
                return ResourceManager.GetString("ApplyTranslations_TextReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to read {0}: {1} 的當地語系化字串。
        /// </summary>
        public static string CollectTranslatableStrings_FailedReading {
            get {
                return ResourceManager.GetString("CollectTranslatableStrings_FailedReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data 的當地語系化字串。
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total Strings: {0} 的當地語系化字串。
        /// </summary>
        public static string GetTranslatableDatStrings_TotalStrings {
            get {
                return ResourceManager.GetString("GetTranslatableDatStrings_TotalStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GGPK Pack File|*.ggpk|Records Bin File|*.bin 的當地語系化字串。
        /// </summary>
        public static string Load_GGPK_Filter {
            get {
                return ResourceManager.GetString("Load_GGPK_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Apply all 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Button_ApplyAll {
            get {
                return ResourceManager.GetString("MainWindow_Button_ApplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Apply all to File 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Button_ApplyAllToFile {
            get {
                return ResourceManager.GetString("MainWindow_Button_ApplyAllToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Revert all 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Button_RevertAll {
            get {
                return ResourceManager.GetString("MainWindow_Button_RevertAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save config 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Button_SaveConfig {
            get {
                return ResourceManager.GetString("MainWindow_Button_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Serialize 的當地語系化字串。
        /// </summary>
        public static string MainWindow_Button_Serialize {
            get {
                return ResourceManager.GetString("MainWindow_Button_Serialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid file filter for GGPK files: {0} 的當地語系化字串。
        /// </summary>
        public static string MainWindow_InvalidFileFilter {
            get {
                return ResourceManager.GetString("MainWindow_InvalidFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translations read: {0} 的當地語系化字串。
        /// </summary>
        public static string ReadTranslationData_Successful {
            get {
                return ResourceManager.GetString("ReadTranslationData_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to load config: {0} 的當地語系化字串。
        /// </summary>
        public static string ReloadAllData_Failed {
            get {
                return ResourceManager.GetString("ReloadAllData_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translations read: {0} 的當地語系化字串。
        /// </summary>
        public static string SaveTranslationData_Successful {
            get {
                return ResourceManager.GetString("SaveTranslationData_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete &apos;{0}&apos;? 的當地語系化字串。
        /// </summary>
        public static string StringEditor_DeleteTranslation {
            get {
                return ResourceManager.GetString("StringEditor_DeleteTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete translation? 的當地語系化字串。
        /// </summary>
        public static string StringEditor_DeleteTranslation_Caption {
            get {
                return ResourceManager.GetString("StringEditor_DeleteTranslation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Original: 的當地語系化字串。
        /// </summary>
        public static string StringEditor_Label_Original {
            get {
                return ResourceManager.GetString("StringEditor_Label_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Replacement: 的當地語系化字串。
        /// </summary>
        public static string StringEditor_Label_Replacement {
            get {
                return ResourceManager.GetString("StringEditor_Label_Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Replacement: 的當地語系化字串。
        /// </summary>
        public static string StringEditor_Label_Translation {
            get {
                return ResourceManager.GetString("StringEditor_Label_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save file before continuing? 的當地語系化字串。
        /// </summary>
        public static string WindowClosing_Save {
            get {
                return ResourceManager.GetString("WindowClosing_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        public static string WindowClosing_Save_Title {
            get {
                return ResourceManager.GetString("WindowClosing_Save_Title", resourceCulture);
            }
        }
    }
}
